apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "velora-operator.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "velora-operator.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "velora-operator.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "velora-operator.selectorLabels" . | nindent 8 }}
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "{{ .Values.metrics.port }}"
    spec:
      serviceAccountName: {{ .Values.serviceAccount.name }}
      securityContext:
        runAsNonRoot: true
        runAsUser: 65532
      containers:
        - name: manager
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
            - /velora-operator
          args:
            - --metrics-bind-address=:{{ .Values.metrics.port }}
            - --health-probe-bind-address=:8081
            - --minio-endpoint={{ .Values.minio.endpoint }}
            - --minio-use-ssl={{ .Values.minio.useSSL }}
            {{- if .Values.leaderElection.enabled }}
            - --leader-elect=true
            {{- end }}
            - --airflow-base-url={{ .Values.airflow.baseURL }}
          env:
            - name: MINIO_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.minio.secretName }}
                  key: access-key
            - name: MINIO_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.minio.secretName }}
                  key: secret-key
            - name: AIRFLOW_USERNAME
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.airflow.secretName }}
                  key: username
            - name: AIRFLOW_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.airflow.secretName }}
                  key: password
          ports:
            - name: metrics
              containerPort: {{ .Values.metrics.port }}
              protocol: TCP
            - name: health
              containerPort: 8081
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /healthz
              port: health
            initialDelaySeconds: 15
            periodSeconds: 20
          readinessProbe:
            httpGet:
              path: /readyz
              port: health
            initialDelaySeconds: 5
            periodSeconds: 10
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
