apiVersion: v1
kind: Secret
metadata:
  name: velora-minio-creds
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  access-key: velora
  secret-key: velora-minio-secret
---
apiVersion: v1
kind: Secret
metadata:
  name: velora-airflow-creds
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  username: admin
  password: admin
