# ArgoCD Application: Apache Airflow
# Managed by the velora-apps App-of-Apps.
# ArgoCD syncs this against gitops/apps/airflow/
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: airflow
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default

  sources:
    - repoURL: https://airflow.apache.org
      chart: airflow
      targetRevision: 1.14.0
      helm:
        releaseName: airflow
        valueFiles:
          - $values/gitops/apps/airflow/values.yaml
    - repoURL: https://github.com/yashasbn/velora.git
      targetRevision: HEAD
      ref: values

  destination:
    server: https://kubernetes.default.svc
    namespace: airflow

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
