# ArgoCD Application: MinIO
# Managed by the velora-apps App-of-Apps.
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: minio
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default

  sources:
    - repoURL: https://charts.bitnami.com/bitnami
      chart: minio
      targetRevision: 14.6.0
      helm:
        releaseName: minio
        valueFiles:
          - $values/gitops/apps/minio/values.yaml
    - repoURL: https://github.com/yashasbn/velora.git
      targetRevision: HEAD
      ref: values

  destination:
    server: https://kubernetes.default.svc
    namespace: minio

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
