apiVersion: v1
kind: Secret
metadata:
  name: velora-repo-config
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
type: Opaque
stringData:
  url: https://github.com/yashasbn/velora.git
  insecure: "true"
  type: git
