/*
Copyright 2026 Velora Authors.
Licensed under the Apache License, Version 2.0.
*/

package controllers_test

import (
	"fmt"
	"path/filepath"
	"runtime"
	"testing"

	. "github.com/onsi/ginkgo/v2"
	. "github.com/onsi/gomega"

	batchv1 "k8s.io/api/batch/v1"
	corev1 "k8s.io/api/core/v1"
	utilruntime "k8s.io/apimachinery/pkg/util/runtime"
	clientgoscheme "k8s.io/client-go/kubernetes/scheme"
	"k8s.io/client-go/rest"
	ctrl "sigs.k8s.io/controller-runtime"
	"sigs.k8s.io/controller-runtime/pkg/client"
	"sigs.k8s.io/controller-runtime/pkg/envtest"
	logf "sigs.k8s.io/controller-runtime/pkg/log"
	"sigs.k8s.io/controller-runtime/pkg/log/zap"

	vv1 "github.com/yashasbn/velora/api/v1alpha1"
	"github.com/yashasbn/velora/controllers"
	fakeairflow "github.com/yashasbn/velora/internal/airflow"
	fakeminio "github.com/yashasbn/velora/internal/minio"
)

// These package-level variables are accessible in the _test.go suite file.
var (
	cfg             *rest.Config
	k8sClient       client.Client
	testEnv         *envtest.Environment
	fakeMinioClient *fakeminio.FakeClient
	fakeAirflow     *fakeairflow.FakeClient
)

func TestControllers(t *testing.T) {
	RegisterFailHandler(Fail)
	RunSpecs(t, "DataPipeline Controller Suite")
}

var _ = BeforeSuite(func() {
	logf.SetLogger(zap.New(zap.WriteTo(GinkgoWriter), zap.UseDevMode(true)))

	By("bootstrapping test environment (envtest)")

	// Point envtest at the CRD manifests generated by controller-gen.
	testEnv = &envtest.Environment{
		CRDDirectoryPaths: []string{
			filepath.Join("..", "..", "config", "crd", "bases"),
		},
		ErrorIfCRDPathMissing: true,
		// Restrict to Go's current OS/arch
		BinaryAssetsDirectory: filepath.Join("..", "..", "bin", "k8s",
			fmt.Sprintf("1.30.0-%s-%s", runtime.GOOS, runtime.GOARCH)),
	}

	var err error
	cfg, err = testEnv.Start()
	Expect(err).NotTo(HaveOccurred())
	Expect(cfg).NotTo(BeNil())

	// Register schemes.
	utilruntime.Must(clientgoscheme.AddToScheme(scheme()))
	utilruntime.Must(vv1.AddToScheme(scheme()))
	utilruntime.Must(batchv1.AddToScheme(scheme()))
	utilruntime.Must(corev1.AddToScheme(scheme()))

	k8sClient, err = client.New(cfg, client.Options{Scheme: scheme()})
	Expect(err).NotTo(HaveOccurred())
	Expect(k8sClient).NotTo(BeNil())

	// Build fake external clients.
	fakeMinioClient = fakeminio.NewFakeClient()
	fakeAirflow = fakeairflow.NewFakeClient()

	// Start the controller manager in the background.
	mgr, err := ctrl.NewManager(cfg, ctrl.Options{
		Scheme: scheme(),
	})
	Expect(err).NotTo(HaveOccurred())

	err = (&controllers.DataPipelineReconciler{
		Client:        mgr.GetClient(),
		Scheme:        mgr.GetScheme(),
		Recorder:      mgr.GetEventRecorderFor("velora-test"),
		MinioClient:   fakeMinioClient,
		AirflowClient: fakeAirflow,
	}).SetupWithManager(mgr)
	Expect(err).NotTo(HaveOccurred())

	go func() {
		defer GinkgoRecover()
		err = mgr.Start(ctrl.SetupSignalHandler())
		Expect(err).NotTo(HaveOccurred())
	}()
})

var _ = AfterSuite(func() {
	By("tearing down test environment")
	Expect(testEnv.Stop()).Should(Succeed())
})

// scheme returns a new runtime.Scheme for tests.
func scheme() *runtime.Scheme {
	return runtime.NewScheme()
}
